// flow-typed signature: c6cc86d172f9967dab27beb8a1a65cd8
// flow-typed version: <<STUB>>/node-forge_v^0.6.46/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-forge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-forge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-forge/js/aes' {
  declare module.exports: any;
}

declare module 'node-forge/js/aesCipherSuites' {
  declare module.exports: any;
}

declare module 'node-forge/js/asn1' {
  declare module.exports: any;
}

declare module 'node-forge/js/cipher' {
  declare module.exports: any;
}

declare module 'node-forge/js/cipherModes' {
  declare module.exports: any;
}

declare module 'node-forge/js/debug' {
  declare module.exports: any;
}

declare module 'node-forge/js/des' {
  declare module.exports: any;
}

declare module 'node-forge/js/forge' {
  declare module.exports: any;
}

declare module 'node-forge/js/form' {
  declare module.exports: any;
}

declare module 'node-forge/js/hmac' {
  declare module.exports: any;
}

declare module 'node-forge/js/http' {
  declare module.exports: any;
}

declare module 'node-forge/js/jsbn' {
  declare module.exports: any;
}

declare module 'node-forge/js/kem' {
  declare module.exports: any;
}

declare module 'node-forge/js/log' {
  declare module.exports: any;
}

declare module 'node-forge/js/md' {
  declare module.exports: any;
}

declare module 'node-forge/js/md5' {
  declare module.exports: any;
}

declare module 'node-forge/js/mgf' {
  declare module.exports: any;
}

declare module 'node-forge/js/mgf1' {
  declare module.exports: any;
}

declare module 'node-forge/js/oids' {
  declare module.exports: any;
}

declare module 'node-forge/js/pbe' {
  declare module.exports: any;
}

declare module 'node-forge/js/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-forge/js/pem' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs1' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs12' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs7' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs7asn1' {
  declare module.exports: any;
}

declare module 'node-forge/js/pki' {
  declare module.exports: any;
}

declare module 'node-forge/js/prime' {
  declare module.exports: any;
}

declare module 'node-forge/js/prime.worker' {
  declare module.exports: any;
}

declare module 'node-forge/js/prng' {
  declare module.exports: any;
}

declare module 'node-forge/js/pss' {
  declare module.exports: any;
}

declare module 'node-forge/js/random' {
  declare module.exports: any;
}

declare module 'node-forge/js/rc2' {
  declare module.exports: any;
}

declare module 'node-forge/js/rsa' {
  declare module.exports: any;
}

declare module 'node-forge/js/sha1' {
  declare module.exports: any;
}

declare module 'node-forge/js/sha256' {
  declare module.exports: any;
}

declare module 'node-forge/js/sha512' {
  declare module.exports: any;
}

declare module 'node-forge/js/socket' {
  declare module.exports: any;
}

declare module 'node-forge/js/ssh' {
  declare module.exports: any;
}

declare module 'node-forge/js/task' {
  declare module.exports: any;
}

declare module 'node-forge/js/tls' {
  declare module.exports: any;
}

declare module 'node-forge/js/tlssocket' {
  declare module.exports: any;
}

declare module 'node-forge/js/util' {
  declare module.exports: any;
}

declare module 'node-forge/js/x509' {
  declare module.exports: any;
}

declare module 'node-forge/js/xhr' {
  declare module.exports: any;
}

declare module 'node-forge/minify' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/build' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/minify' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/server' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/aes' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/asn1' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/browser' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/csr' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/des' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/hmac' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/kem' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/md5' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/mgf1' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/pem' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/pkcs1' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/pkcs12' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/pkcs7' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/random' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/rc2' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/rsa' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/sha1' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/sha256' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/sha512' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/ssh' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/tls' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/util' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/test/x509' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/ui/require' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/ui/test' {
  declare module.exports: any;
}

declare module 'node-forge/nodejs/ui/test.min' {
  declare module.exports: any;
}

declare module 'node-forge/tests/aes-speed' {
  declare module.exports: any;
}

declare module 'node-forge/tests/common' {
  declare module.exports: any;
}

declare module 'node-forge/tests/form' {
  declare module.exports: any;
}

declare module 'node-forge/tests/heartbleed' {
  declare module.exports: any;
}

declare module 'node-forge/tests/issue-428' {
  declare module.exports: any;
}

declare module 'node-forge/tests/loginDemo' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-create-cert' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-create-csr' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-create-pkcs12' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-imap' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-sign-p7' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-tls' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-ws-webid' {
  declare module.exports: any;
}

declare module 'node-forge/tests/nodejs-ws' {
  declare module.exports: any;
}

declare module 'node-forge/tests/tasks' {
  declare module.exports: any;
}

declare module 'node-forge/tests/webid' {
  declare module.exports: any;
}

declare module 'node-forge/tests/ws-webid' {
  declare module.exports: any;
}

declare module 'node-forge/tests/ws' {
  declare module.exports: any;
}

declare module 'node-forge/tests/xhr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-forge/js/aes.js' {
  declare module.exports: $Exports<'node-forge/js/aes'>;
}
declare module 'node-forge/js/aesCipherSuites.js' {
  declare module.exports: $Exports<'node-forge/js/aesCipherSuites'>;
}
declare module 'node-forge/js/asn1.js' {
  declare module.exports: $Exports<'node-forge/js/asn1'>;
}
declare module 'node-forge/js/cipher.js' {
  declare module.exports: $Exports<'node-forge/js/cipher'>;
}
declare module 'node-forge/js/cipherModes.js' {
  declare module.exports: $Exports<'node-forge/js/cipherModes'>;
}
declare module 'node-forge/js/debug.js' {
  declare module.exports: $Exports<'node-forge/js/debug'>;
}
declare module 'node-forge/js/des.js' {
  declare module.exports: $Exports<'node-forge/js/des'>;
}
declare module 'node-forge/js/forge.js' {
  declare module.exports: $Exports<'node-forge/js/forge'>;
}
declare module 'node-forge/js/form.js' {
  declare module.exports: $Exports<'node-forge/js/form'>;
}
declare module 'node-forge/js/hmac.js' {
  declare module.exports: $Exports<'node-forge/js/hmac'>;
}
declare module 'node-forge/js/http.js' {
  declare module.exports: $Exports<'node-forge/js/http'>;
}
declare module 'node-forge/js/jsbn.js' {
  declare module.exports: $Exports<'node-forge/js/jsbn'>;
}
declare module 'node-forge/js/kem.js' {
  declare module.exports: $Exports<'node-forge/js/kem'>;
}
declare module 'node-forge/js/log.js' {
  declare module.exports: $Exports<'node-forge/js/log'>;
}
declare module 'node-forge/js/md.js' {
  declare module.exports: $Exports<'node-forge/js/md'>;
}
declare module 'node-forge/js/md5.js' {
  declare module.exports: $Exports<'node-forge/js/md5'>;
}
declare module 'node-forge/js/mgf.js' {
  declare module.exports: $Exports<'node-forge/js/mgf'>;
}
declare module 'node-forge/js/mgf1.js' {
  declare module.exports: $Exports<'node-forge/js/mgf1'>;
}
declare module 'node-forge/js/oids.js' {
  declare module.exports: $Exports<'node-forge/js/oids'>;
}
declare module 'node-forge/js/pbe.js' {
  declare module.exports: $Exports<'node-forge/js/pbe'>;
}
declare module 'node-forge/js/pbkdf2.js' {
  declare module.exports: $Exports<'node-forge/js/pbkdf2'>;
}
declare module 'node-forge/js/pem.js' {
  declare module.exports: $Exports<'node-forge/js/pem'>;
}
declare module 'node-forge/js/pkcs1.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs1'>;
}
declare module 'node-forge/js/pkcs12.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs12'>;
}
declare module 'node-forge/js/pkcs7.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs7'>;
}
declare module 'node-forge/js/pkcs7asn1.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs7asn1'>;
}
declare module 'node-forge/js/pki.js' {
  declare module.exports: $Exports<'node-forge/js/pki'>;
}
declare module 'node-forge/js/prime.js' {
  declare module.exports: $Exports<'node-forge/js/prime'>;
}
declare module 'node-forge/js/prime.worker.js' {
  declare module.exports: $Exports<'node-forge/js/prime.worker'>;
}
declare module 'node-forge/js/prng.js' {
  declare module.exports: $Exports<'node-forge/js/prng'>;
}
declare module 'node-forge/js/pss.js' {
  declare module.exports: $Exports<'node-forge/js/pss'>;
}
declare module 'node-forge/js/random.js' {
  declare module.exports: $Exports<'node-forge/js/random'>;
}
declare module 'node-forge/js/rc2.js' {
  declare module.exports: $Exports<'node-forge/js/rc2'>;
}
declare module 'node-forge/js/rsa.js' {
  declare module.exports: $Exports<'node-forge/js/rsa'>;
}
declare module 'node-forge/js/sha1.js' {
  declare module.exports: $Exports<'node-forge/js/sha1'>;
}
declare module 'node-forge/js/sha256.js' {
  declare module.exports: $Exports<'node-forge/js/sha256'>;
}
declare module 'node-forge/js/sha512.js' {
  declare module.exports: $Exports<'node-forge/js/sha512'>;
}
declare module 'node-forge/js/socket.js' {
  declare module.exports: $Exports<'node-forge/js/socket'>;
}
declare module 'node-forge/js/ssh.js' {
  declare module.exports: $Exports<'node-forge/js/ssh'>;
}
declare module 'node-forge/js/task.js' {
  declare module.exports: $Exports<'node-forge/js/task'>;
}
declare module 'node-forge/js/tls.js' {
  declare module.exports: $Exports<'node-forge/js/tls'>;
}
declare module 'node-forge/js/tlssocket.js' {
  declare module.exports: $Exports<'node-forge/js/tlssocket'>;
}
declare module 'node-forge/js/util.js' {
  declare module.exports: $Exports<'node-forge/js/util'>;
}
declare module 'node-forge/js/x509.js' {
  declare module.exports: $Exports<'node-forge/js/x509'>;
}
declare module 'node-forge/js/xhr.js' {
  declare module.exports: $Exports<'node-forge/js/xhr'>;
}
declare module 'node-forge/minify.js' {
  declare module.exports: $Exports<'node-forge/minify'>;
}
declare module 'node-forge/nodejs/build.js' {
  declare module.exports: $Exports<'node-forge/nodejs/build'>;
}
declare module 'node-forge/nodejs/minify.js' {
  declare module.exports: $Exports<'node-forge/nodejs/minify'>;
}
declare module 'node-forge/nodejs/server.js' {
  declare module.exports: $Exports<'node-forge/nodejs/server'>;
}
declare module 'node-forge/nodejs/test/aes.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/aes'>;
}
declare module 'node-forge/nodejs/test/asn1.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/asn1'>;
}
declare module 'node-forge/nodejs/test/browser.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/browser'>;
}
declare module 'node-forge/nodejs/test/csr.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/csr'>;
}
declare module 'node-forge/nodejs/test/des.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/des'>;
}
declare module 'node-forge/nodejs/test/hmac.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/hmac'>;
}
declare module 'node-forge/nodejs/test/kem.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/kem'>;
}
declare module 'node-forge/nodejs/test/md5.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/md5'>;
}
declare module 'node-forge/nodejs/test/mgf1.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/mgf1'>;
}
declare module 'node-forge/nodejs/test/pbkdf2.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/pbkdf2'>;
}
declare module 'node-forge/nodejs/test/pem.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/pem'>;
}
declare module 'node-forge/nodejs/test/pkcs1.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/pkcs1'>;
}
declare module 'node-forge/nodejs/test/pkcs12.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/pkcs12'>;
}
declare module 'node-forge/nodejs/test/pkcs7.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/pkcs7'>;
}
declare module 'node-forge/nodejs/test/random.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/random'>;
}
declare module 'node-forge/nodejs/test/rc2.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/rc2'>;
}
declare module 'node-forge/nodejs/test/rsa.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/rsa'>;
}
declare module 'node-forge/nodejs/test/sha1.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/sha1'>;
}
declare module 'node-forge/nodejs/test/sha256.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/sha256'>;
}
declare module 'node-forge/nodejs/test/sha512.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/sha512'>;
}
declare module 'node-forge/nodejs/test/ssh.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/ssh'>;
}
declare module 'node-forge/nodejs/test/tls.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/tls'>;
}
declare module 'node-forge/nodejs/test/util.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/util'>;
}
declare module 'node-forge/nodejs/test/x509.js' {
  declare module.exports: $Exports<'node-forge/nodejs/test/x509'>;
}
declare module 'node-forge/nodejs/ui/require.js' {
  declare module.exports: $Exports<'node-forge/nodejs/ui/require'>;
}
declare module 'node-forge/nodejs/ui/test.js' {
  declare module.exports: $Exports<'node-forge/nodejs/ui/test'>;
}
declare module 'node-forge/nodejs/ui/test.min.js' {
  declare module.exports: $Exports<'node-forge/nodejs/ui/test.min'>;
}
declare module 'node-forge/tests/aes-speed.js' {
  declare module.exports: $Exports<'node-forge/tests/aes-speed'>;
}
declare module 'node-forge/tests/common.js' {
  declare module.exports: $Exports<'node-forge/tests/common'>;
}
declare module 'node-forge/tests/form.js' {
  declare module.exports: $Exports<'node-forge/tests/form'>;
}
declare module 'node-forge/tests/heartbleed.js' {
  declare module.exports: $Exports<'node-forge/tests/heartbleed'>;
}
declare module 'node-forge/tests/issue-428.js' {
  declare module.exports: $Exports<'node-forge/tests/issue-428'>;
}
declare module 'node-forge/tests/loginDemo.js' {
  declare module.exports: $Exports<'node-forge/tests/loginDemo'>;
}
declare module 'node-forge/tests/nodejs-create-cert.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-create-cert'>;
}
declare module 'node-forge/tests/nodejs-create-csr.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-create-csr'>;
}
declare module 'node-forge/tests/nodejs-create-pkcs12.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-create-pkcs12'>;
}
declare module 'node-forge/tests/nodejs-imap.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-imap'>;
}
declare module 'node-forge/tests/nodejs-sign-p7.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-sign-p7'>;
}
declare module 'node-forge/tests/nodejs-tls.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-tls'>;
}
declare module 'node-forge/tests/nodejs-ws-webid.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-ws-webid'>;
}
declare module 'node-forge/tests/nodejs-ws.js' {
  declare module.exports: $Exports<'node-forge/tests/nodejs-ws'>;
}
declare module 'node-forge/tests/tasks.js' {
  declare module.exports: $Exports<'node-forge/tests/tasks'>;
}
declare module 'node-forge/tests/webid.js' {
  declare module.exports: $Exports<'node-forge/tests/webid'>;
}
declare module 'node-forge/tests/ws-webid.js' {
  declare module.exports: $Exports<'node-forge/tests/ws-webid'>;
}
declare module 'node-forge/tests/ws.js' {
  declare module.exports: $Exports<'node-forge/tests/ws'>;
}
declare module 'node-forge/tests/xhr.js' {
  declare module.exports: $Exports<'node-forge/tests/xhr'>;
}
